version: '3.9'

services:
  api:
    container_name: next-insta-api
    build:
      context: .
    ports:
      - '8080:1337'
    command: yarn dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - SERVER_PORT=1337
      - DB_HOSTNAME=db
      - DB_PORT=5432
      - DB_NAME=db
      - DB_USERNAME=user
      - DB_PASSWORD=pass
      - REDIS_URL=redis://cache:6379
    depends_on:
      - db
      - cache
  db:
    container_name: next-insta-db
    image: postgres:14.2-alpine
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  cache:
    container_name: next-insta-cache
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
